# Generated by Django 2.2.3 on 2019-08-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190820_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='exercise',
            field=models.CharField(choices=[('pullup', 'pullup'), ('pushup', 'pushup'), ('row', 'row'), ('squat', 'squat')], default='pullup', max_length=100),
        ),
    ]
